---
- hosts: localhost
  user: root
  pre_tasks:
    - name: be sure apt cache is updated
      apt: update_cache=yes

  vars:
    domjudge_api_endpoint: http://some-endpoint.example.com/api
    domjudge_api_endpoint_user: judgehost
    domjudge_api_endpoint_pass: judgehost_pass
    domjudge_repo: 'deb http://domjudge.org/debian unstable/'
    domjudge_repo_key: 'http://domjudge.org/repokey.asc'

  tasks:

    - name: install judgehost dependencies
      apt: pkg={{ item }} state=present
      with_items:
        - php-cli
        - php-json
        - php-curl
        - procps
        - bash-static
        - adduser
        - unzip
        - libcgroup1
        - python-pip

    - name: install awscli
      pip: name=awscli state=present

    - name: debconf seed judgehost setup
      debconf: name='{{ item['name'] }}' question='{{ item['question'] }}' value='{{ item.value }}' vtype='{{ item.type }}'
      tags: domjudge-judgehost
      with_items:
          - name: domjudge-judgehost
            question: 'domjudge/api_endpoint'
            value: "{{ domjudge_api_endpoint }}"
            type: password
          - name: domjudge-judgehost
            question: 'domjudge/api_endpoint_user'
            value: "{{ domjudge_api_endpoint_user }}"
            type: string
          - name: domjudge-judgehost
            question: 'domjudge/api_endpoint_pass'
            value: "{{ domjudge_api_endpoint_pass }}"
            type: string

    - name: copy helper script for running judgedaemons
      copy: src=files/spawn_judgedaemons dest=/usr/local/sbin/spawn_judgedaemons mode=0755

    - name: install our own systemd init scripts
      copy: src=files/{{item}} dest=/etc/systemd/system/{{item}}
      with_items:
        - judgedaemon-instance@.service
        - judgedaemons.service

    - name: enable swap accounting(for cgroups)
      lineinfile: dest=/etc/default/grub.d/50-cloudimg-settings.cfg regexp="^GRUB_CMDLINE_LINUX_DEFAULT=" line='GRUB_CMDLINE_LINUX_DEFAULT="console=tty1 console=ttyS0 swapaccount=1"' state=present
      notify: update grub

    - name: install debootstrap which is used when making the chroot
      apt: pkg=debootstrap state=latest
      tags: domjudge-judgehost

    - name: setup the chroot
      script: files/make_chroot /var/lib/domjudge/javachroot/ creates=/var/lib/domjudge/javachroot/
      tags: domjudge-judgehost
      environment:
        DEBMIRROR: http://us-east-1.ec2.archive.ubuntu.com/ubuntu

    - name: install compilers
      apt: pkg={{ item }} state=present
      with_items:
        - build-essential           # c/c++
        #- ghc                       # haskell
        #- fpc                       # pascal
        #- python                    # python 2.7
        #- python3                   # python 3
        #- gnat                      # gnu ada
        #- gfortran                  # fortran
        #- mono-complete             # c#
        #- fsharp                    # fsharp
        #- lua5.2                    # lua
        - openjdk-8-jdk             # jdk8
        #- gccgo                     # go reference compiler
        #- golang                    # go using gcc
        #- ruby                      # ruby
        #- nodejs                    # javascript
        #- gdc                       # D
        #- scala                     # Scala

    - name: copy deployment script
      copy: src=files/deploy_judgehost.sh dest=/root/deploy_judgehost.sh mode=0755

    - name: do something with ufw
      ufw: logging=off
      tags: ['domjudge-judgehost', 'ufw']

  handlers:
    - name: update grub
      command: /usr/sbin/update-grub
